src/ecom2/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

# from products.views import ProductListView, ProductDetailView, ProductFeaturedListView, ProductFeaturedDetailView

from .views import home_page, contact_page, about_page, login_page, register_page, logout_page, password_change

urlpatterns = [
    url(r'^$', home_page,name='home'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^about/$', about_page,name='about'),
    url(r'^login/$', login_page,name='login'),
    url(r'^logout/$', logout_page,name='logout'),
    url(r'^changepass/$', password_change,name='password_change'),
    url(r'^products/', include("products.urls",namespace='products')),
    url(r'^search/', include("search.urls",namespace='search')),
    # url(r'^products/$', ProductListView),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailView),
    # # url(r'^products/(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDetailSlugView),
    # url(r'^featured/$', ProductFeaturedListView),
    # url(r'^featured/(?P<slug>[\w-]+)/$', ProductFeaturedDetailView),

    url(r'^register/$', register_page,name='register'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import ProductListView, ProductDetailView, ProductFeaturedListView, ProductFeaturedDetailView

urlpatterns = [
    url(r'^$', ProductListView,name='list'),
    url(r'^featured/$', ProductFeaturedListView,name='f_list'),
    url(r'^featured/(?P<slug>[\w-]+)/$', ProductFeaturedDetailView,name='f_detail'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView,name='detail'),
]

src/search/urls.py
from django.conf.urls import url

from .views import SearchProductView

urlpatterns = [
    url(r'^$', SearchProductView,name='query')
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- My CSS -->
<link rel="stylesheet" href='{% static "css/main.css" %}' >

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'logout' as logout_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'products:f_list' as featured_products_list_url %}
{% url 'about' as about_url %}
{% url 'search:query' as search_url %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
  <a class="navbar-brand" href="{{ home_url }}">
  <img src="{% static 'img/SSlogo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="StatShop">
  eCommerce
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown {% if request.path == products_list_url %}active{% elif request.path == featured_products_list_url %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="{{ products_list_url }}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Purchase
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ products_list_url }}">Products</a>
          <a class="dropdown-item" href="{{ featured_products_list_url }}">Exclusive Products</a>
        </div>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link" href="{{ about_url }}">About Us</a>
      </li>
      <li class="nav-item dropdown {% if request.path == login_url %}active{% elif request.path == logout_url %}active{% elif request.path == register_url %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="{{ login_url }}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          {% if request.user.is_authenticated %}
          <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
          {% else %}
          <a class="dropdown-item" href="{{ login_url }}">Login</a>
          <a class="dropdown-item" href="{{ register_url }}">Register</a>
          {% endif %}
        </div>
      </li>
    </ul>
      {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>